#!/bin/zsh
SELF="${0:A}"
# 其餘 12 個立繪基底（2:3 直幅）。用法: genchar2.sh <key> [<key> ...]
# STYLE / FRAME / RULES 與 genchar.sh 一字不差——差一個字，這批就跟前三張
# 不是同一套人。龐貝第 5 輪就是這樣作廢的。
OUT="${SELF:h}/../美術測試"

STYLE="A PAINTED FIGURE STUDY FOR A HISTORICAL RECONSTRUCTION ILLUSTRATION OF PARIS AND VERSAILLES IN OCTOBER 1789. This is a PAINTING, not a photograph. Painted by the same hand that paints the architectural reconstruction views: realistic digital matte painting, visible painterly handling in the fabric folds and the skin, softly painted edges, matte surface, no photographic depth of field, no lens blur, no studio vignette, no glossy highlights on the skin. Late-18th-century French palette — wet pale limestone, slate blue-grey, rain-desaturated green, mud brown, undyed and indigo and russet wool, with dull crimson as the only warm accent. Low contrast, muted saturation, overcast light."

FRAME="This is a VISUAL NOVEL CHARACTER SPRITE for a mobile game, PORTRAIT orientation aspect ratio 2:3. FRAMING, follow exactly: the top of the head sits about 8 percent down from the top edge; the figure is CROPPED AT THE WAIST at the bottom edge; the figure is CENTRED horizontally and fills about 70 percent of the frame width; the body is turned very slightly to one side, the head upright, the eyes looking at the viewer. LIGHTING, follow exactly: one soft key light from the UPPER LEFT at about 45 degrees, producing a visible soft shadow down the RIGHT side of the face and the RIGHT side of the neck; even flat illustration lighting elsewhere; NO rim light, NO dramatic chiaroscuro. BACKGROUND, follow exactly: one single completely FLAT UNIFORM MEDIUM GREY FIELD filling the entire background, absolutely even, NO vignette, NO gradient, NO darkening at the corners, NO cast shadow behind the figure, NO scenery. Expression: neutral and at rest, mouth closed - this is the base pose from which expression variants will be derived."

RULES="Historical accuracy for France in OCTOBER 1789, before the Revolution had names for its sides. WOMEN wear layered dress: a linen shift, a stiffened supporting bodice giving a firm shaped waist (working women wore these too - NOT a loose unsupported peasant smock), a fitted short jacket or plain gown, a coarse apron tied at the waist, a folded linen kerchief covering the chest and tucked into the front, and a linen cap covering most of the hair. MEN wear knee breeches with stockings, a linen shirt, a long waistcoat and a coat - NEVER long trousers. Wool and linen, undyed or indigo or russet or brown; no silk, no lace, no embroidery on common people. EVERYONE has something on their head. NO red Phrygian cap, NO tricolour sash, NO Napoleonic uniform, NO guillotine - all of those are years later. NO eyeglasses, NO modern hairstyle, NO modern makeup. NO text, NO lettering, NO watermark, NO signature, NO border. Avoid: photograph, photorealistic portrait photography, studio headshot, anime, cel shading, plastic skin, medieval or Renaissance costume, Victorian dress, fantasy costume, landscape orientation."

case "$1" in
# ══ 1️⃣ 擋板 ═══════════════════════════════════════════════════════════
anne) F="ch_anne_base"; S="THE CHARACTER: Anne Fauchet, about forty, wife of a Paris baker — the shop was her father's and she keeps the counter and the money. Build: compact, strong forearms from lifting trays. Face: pale skin flushed and slightly shiny from standing beside an oven, brown hair pulled back tight under a plain linen cap, level unsentimental eyes, mouth closed and steady. She is the one who has to say 'there is none' to forty people. Dress: a fitted short jacket of dark brown wool over a linen shift with a firm shaped waist; a WHITE floury apron, clean but permanently dusted; a linen kerchief crossed at the chest. A pair of counter-worn hands.";;

jacquot) F="ch_jacquot_base"; S="THE CHARACTER: Jacquot, a thirteen-year-old baker's apprentice in Paris, three years in the trade. Build: thin, small for his age, but with forearms and hands already thickened and calloused from kneading. Face: young pale skin, dark hair cut short and badly, flour caught in his eyebrows and at his hairline, large watchful eyes, mouth closed. He is tired in the way only someone who gets up at three can be. Dress: a linen shirt with the sleeves rolled high, a coarse waistcoat, knee breeches and wool stockings, and a long undyed apron reaching below the knee, white with flour. A knitted cap pushed back on his head. Everything slightly too big for him.";;

bertin) F="ch_bertin_base"; S="THE CHARACTER: Madame Bertin, about fifty-five, who keeps a cloth shop on the same Paris street and has bought from this bakery for twenty years. Build: upright, contained, careful of her appearance. Face: pale well-kept skin, grey hair neatly dressed under a fine white linen cap with a small frill, direct eyes that expect to be recognised, mouth held pleasantly but firmly. Dress: BETTER THAN THE OTHERS BUT NOT BY MUCH — a well-cut fitted jacket of good grey-blue wool, a clean fine-linen kerchief, a dark petticoat without patches, a small plain brooch at the throat. Respectable trade, not gentry.";;

# ══ 3️⃣ 柵欄的兩邊 ═════════════════════════════════════════════════════
# ✅ 制服已查證：深藍外套＋紅翻邊＋紅背心紅馬褲＋**銀色**飾帶。
officer) F="ch_officer_base"; S="THE CHARACTER: a lieutenant of the French royal bodyguard at Versailles, about forty. He is an officer of an exclusively noble corps but he is not a courtier — he has been on duty in the rain since noon. Build: upright, spare, weathered. Face: pale skin reddened by weather, dark hair greying at the temples and tied back plainly without powder, clean shaven, tired attentive eyes, a mouth that has been giving orders it does not understand. UNIFORM, follow exactly: a DARK BLUE military coat with RED cuffs and RED lining, heavily trimmed with SILVER braid (silver, never gold); a RED waistcoat; a broad buff leather bandolier across the chest; a black tricorne hat. Soaked through with rain, the silver braid dulled and dark with water.";;

guard) F="ch_guard_base"; S="THE CHARACTER: a young trooper of the French royal bodyguard at Versailles, twenty-four, four years in service — the second son of impoverished provincial gentry whose family beggared themselves buying his horse and equipment. He is noble and he is poor, and both show. Build: lean, straight-backed, not heavy. Face: pale, fine-boned, dark hair tied back plainly without powder, clean shaven, young eyes that are trying not to look at anything in particular. UNIFORM, follow exactly: a DARK BLUE military coat with RED cuffs and RED lining, trimmed with SILVER braid (silver, never gold); a RED waistcoat; a buff leather bandolier; a black tricorne hat. The coat is correct but visibly the cheapest version of itself, and it is soaked through.";;

# ══ 4️⃣ 三天份的行李 ═══════════════════════════════════════════════════
suzanne) F="ch_suzanne_base"; S="THE CHARACTER: Suzanne, about forty-five, a servant in the royal household at Versailles for fifteen years. NOT a costumed maid — 1789 has no maid's uniform: she wears ordinary women's dress of good quality. Build: neat, economical in movement. Face: pale indoor skin, brown hair greying and pinned smoothly under a neat white linen cap, eyes that have learned to see everything and report none of it, mouth closed and unreadable. Dress: a well-cut fitted jacket of fine grey wool; a CLEAN WHITE fine-linen apron; a white linen kerchief folded smooth across the chest; no silk, no lace, no embroidery. She reads as a respectable townswoman.";;

gervais) F="ch_gervais_base"; S="THE CHARACTER: Madame Gervais, about fifty-five, the senior woman who runs the linen and wardrobe of a great household at Versailles — she gives the orders to the other servants and receives them from above. NOT a costumed maid. Build: upright, still, hands folded. Face: pale, spare, grey hair severely smooth under a very neat white cap, deep-set eyes that give nothing away, mouth a controlled line. She is holding several things she is not saying. Dress: a plain gown of fine dark grey wool, better cut than the servants under her; a clean white apron; a white kerchief; a small ring of keys at her waist. Sober, immaculate, no ornament.";;

etienne) F="ch_etienne_base"; S="THE CHARACTER: Étienne Renaud, fifty-four, a lower household servant at Versailles who has worked there thirty-nine years — his father worked there before him. His job is the doors, the windows and the lighting. Build: stooped a little, thin, careful. Face: pale indoor skin, deeply lined, grey hair tied back plainly at the nape (no powder), clean shaven, patient eyes, a mouth that does not expect to be asked anything. Dress: a PLAIN DARK COAT of good but old wool over a long waistcoat and linen shirt, knee breeches and stockings. NO braid, NO badge, NO coloured facings, NO livery of any kind. He carries a brass candlestick.";;

# ══ 5️⃣ 陽台 ═══════════════════════════════════════════════════════════
sergeant) F="ch_sergeant_base"; S="THE CHARACTER: a sergeant of the newly formed Paris National Guard, about thirty-five, a locksmith by trade until three months ago. THE GUARD WAS FORMED IN JULY 1789 AND UNIFORMS WERE NOT YET GENERALLY ISSUED: he wears his OWN CLOTHES with a cockade, not a uniform. Build: thick through the shoulders, a working man. Face: weathered, dark stubble, dark hair tied back, brows drawn — a man who has been given an order he cannot interpret and has to pass it on anyway. Dress: his own linen shirt, a long brown waistcoat, a dark coat that does not match it, knee breeches and stockings. A TRICOLOUR COCKADE pinned to a plain black hat — the only thing on him that says which side he is on. A musket sling over one shoulder.";;

# ══ 6️⃣ 牛奶 ═══════════════════════════════════════════════════════════
gardener) F="ch_gardener_base"; S="THE CHARACTER: an old man of about sixty-five who prunes and clips in the gardens of Versailles, and has done for forty years. Build: small, bent, wiry, hands enormous relative to his frame. Face: deeply weathered brown skin, white stubble, white hair under a shapeless broad-brimmed felt hat, pale eyes narrowed from a lifetime outdoors, mouth pulled in. Entirely unimpressed by anything. Dress: a coarse UNDYED linen smock over a brown wool waistcoat, knee breeches, thick stockings; everything unbleached, brown and grey, the LOWEST SATURATION of any figure. He holds a pair of long-handled iron pruning shears. Real working clothes, not pastoral costume.";;

# ══ 7️⃣ 麵包師傅一家 ═══════════════════════════════════════════════════
womana) F="ch_womana_base"; S="THE CHARACTER: a Paris woman of about thirty-five walking back from Versailles in the procession, talking without stopping. Build: sturdy, energetic even after twenty kilometres. Face: pale skin reddened by weather and exertion, brown hair escaping from a limp linen cap, bright quick eyes, mouth open mid-sentence, an expression of certainty about something she does not actually know. Dress: a fitted short jacket of russet wool over a linen shift with a shaped supporting waist; a mud-heavy petticoat; a coarse apron; a linen kerchief. A TRICOLOUR COCKADE on her cap. Soaked, muddy to the knee, and entirely undefeated.";;

# ══ 8️⃣ 今晚不點了 ═════════════════════════════════════════════════════
clerk) F="ch_clerk_base"; S="THE CHARACTER: a clerk of about thirty sent to inventory the contents of the palace after the court has gone. He is not important and he knows it; he is careful, incurious and in a hurry. Build: slight, indoor, slightly round-shouldered. Face: pale, clean shaven, thin brown hair tied back plainly, spectacle-free, eyes already back on his paper before you have finished answering, mouth neutral. Dress: a plain dark bottle-green wool coat over a long waistcoat, linen shirt with a white neckcloth, knee breeches and stockings. He carries a stack of loose papers and a portable inkhorn. Neat, cheap, entirely functional.";;


# ══ 2️⃣ 的主角，在 3️⃣ 與 7️⃣ 需要露臉 ═════════════════════════════════
marguerite) F="ch_marguerite_base"; S="THE CHARACTER: Marguerite Roussel, a Paris fishwife of about thirty-five who has just walked twenty kilometres through rain. Build: strong through the shoulders and forearms, a woman who lifts crates of wet fish every morning. Face: pale skin reddened raw across the cheekbones and nose by wind and rain; mid-brown hair soaked dark and plastered at the temples, escaping from under a limp linen cap; level direct eyes with dark rings under them; mouth closed, jaw set. She is soaked to the skin and she is not complaining about it. Dress: a fitted short jacket of indigo wool, black with water, over a linen shift with a firm shaped waist; a coarse apron; a linen kerchief crossed at the chest, wet through. A TRICOLOUR COCKADE pinned to her cap, SOAKED AND RUINED so that the blue, white and red have bled into each other and can no longer be told apart.";;

*) echo "unknown: $1"; echo "可用: anne jacquot bertin officer guard suzanne gervais etienne sergeant gardener womana clerk marguerite"; exit 1;;
esac

cd "$OUT" || exit 1
codex exec --skip-git-repo-check --sandbox workspace-write \
  "Use your image_gen tool to generate ONE image in PORTRAIT orientation aspect ratio 2:3 (about 1024x1536), then copy the generated file into the current directory as ${F}.png using cp, then run ls to verify it exists. Use this prompt: ${STYLE} ${FRAME} ${S} ${RULES}" 2>&1 | tail -2

shift
if [ $# -gt 0 ]; then exec "$SELF" "$@"; fi
