#!/bin/zsh
SELF="${0:A}"
# 剩餘 4 張場景圖（直式 9:16）。用法: genbg2.sh <key> [<key> ...]
OUT="${SELF:h}/../美術測試"

STYLE="realistic digital matte painting, archaeological reconstruction illustration, high detail, subtle painterly finish, not photographic, Roman fresco palette of red ochre, yellow ochre, Egyptian blue, green earth, lime white, warm Mediterranean light, naturalistic soft shadows, muted saturation. VERTICAL PORTRAIT composition 9:16."

RULES="COMPOSITION: mobile phone visual novel background in PORTRAIT 9:16. The base of the main subject sits at about 60 percent of image height; the lower 35 percent is low-information texture (ground, ash, water) - not empty flat colour, not important props. NO PEOPLE. NO TEXT or lettering. Avoid: anime, gothic or pointed arches, medieval, Renaissance, bell towers, church domes, modern objects, watermarks, landscape orientation."

case "$1" in
column) F="cg_column_rising"; S="THE SUBJECT IS THE ERUPTION COLUMN OF VESUVIUS ON THE AFTERNOON OF THE ERUPTION IN 79 AD, seen from a distance across the bay. The tall vertical frame is perfect for this: a single enormous WHITE-GREY COLUMN of ash rises dead straight from the mountain summit, filling the height of the frame, and at the very top it spreads out into many branches like an UMBRELLA PINE TREE - this is the shape the only eyewitness compared it to. The column is brilliant white where the sun catches it and dirty grey in shadow; deep inside its base there are dull red glows and flickers of lightning. At the bottom of the frame, small and low, the green cone of the mountain and a sliver of the town and the sea. THE MOUNTAIN ITSELF must still be an intact green cone with terraced vineyards - the summit is not yet blown open, the column rises from it. Sunlight from the side, the sky around still blue at the edges and darkening near the column. Overwhelming scale.";;
ash) F="bg_street_ash"; S="THE SUBJECT IS THE SAME NARROW POMPEIAN STREET AS bg_street, NOW BURIED IN FALLING PUMICE, at what should be daylight but is dark as dusk. White-grey pumice stones have piled up to KNEE HEIGHT along the whole street, burying the stepping stones and the raised sidewalks so the street reads as one smooth pale slope. Pumice is still falling through the air, small pale flecks. Painted red and yellow ochre walls above the drift, dulled under a film of grey ash. A cloth awning has collapsed under the weight. A doorway is half blocked by the drift. One oil lamp burning in a doorway is the only warm light. Terracotta roof tiles sagging under a load of pumice. Dim, colourless, oppressive - but keep the ochre walls readable.";;
collapse) F="bg_atrium_collapse"; S="THE SUBJECT IS THE ATRIUM OF A ROMAN HOUSE DURING THE ERUPTION, at night, the roof beginning to fail. The square compluvium opening above is choked with pale pumice; a long CRACK runs diagonally across the coffered timber ceiling and fine grey ash pours down through it in a thin steady stream. Pumice has spilled through the opening and half filled the impluvium basin below, the water gone grey. Fourth-Style red and yellow ochre wall panels still bright where the ash has not settled. A bronze oil lamp on a tall stand gives the only light, very still and vertical. A cupboard of wooden writing tablets against the wall. Dust in the lamplight. Silence and imminent weight.";;
puteoli) F="bg_puteoli"; S="THE SUBJECT IS THE ATRIUM OF A NEWLY BOUGHT ROMAN TOWNHOUSE IN PUTEOLI, months after the eruption, early morning. It is LARGER and NEWER than a Pompeian house: a wide square compluvium opening letting in strong clean morning light, a crisp rectangular impluvium, a brand-new geometric mosaic floor with no patches and no wear. THE KEY DETAIL: THE WALLS ARE BARE WHITE PLASTER, completely UNPAINTED - no frescoes, no panels, no decoration at all, just clean white lime plaster. This is deliberate and must be obvious. A few pieces of good furniture, a stack of new empty two-handled amphorae against one wall, a single bronze lamp stand. Everything is new, expensive and impersonal. Bright, airy, and slightly cold despite the warm light.";;
*) echo "unknown: $1"; exit 1;;
esac

cd "$OUT" || exit 1
codex exec --skip-git-repo-check --sandbox workspace-write "Use your image_gen tool to generate ONE image in PORTRAIT orientation aspect ratio 9:16 (about 1024x1792), then copy the generated file into the current directory as ${F}.png using cp, then run ls to verify. Use this prompt: ${STYLE} ${S} ${RULES}" 2>&1 | tail -2

shift
if [ $# -gt 0 ]; then exec "$SELF" "$@"; fi
