#!/bin/zsh
SELF="${0:A}"
# 產出龐貝景點包的直式背景（9:16）。用法: genbg.sh <key> [<key> ...]
OUT="${SELF:h}/../美術測試"

STYLE="realistic digital matte painting, archaeological reconstruction illustration, high detail, subtle painterly finish, not photographic, Roman fresco palette of red ochre, yellow ochre, Egyptian blue, green earth, lime white, warm Mediterranean light, naturalistic soft shadows, muted saturation. VERTICAL PORTRAIT composition 9:16."

RULES="IMPORTANT COMPOSITION RULES: this is a mobile phone visual novel background in PORTRAIT 9:16. The main visual focus and anything that identifies the place must sit in the UPPER HALF of the frame. The LOWER 35 percent must be simple ground, floor or water with nothing important in it, because a dialogue box will cover it - but do not leave more than 40 percent empty. Use the tall frame for vertical subjects: columns, high walls, ceiling openings, vaults. Walls are PAINTED red ochre and yellow ochre with a dark socle band, never bare white marble. Terracotta roof tiles. Small barred wooden openings only - NO glazed gridded windows. Include signs of daily life through props: cloth awnings, hanging laundry, water troughs, worn thresholds, stacked pottery, layered painted graffiti. NO PEOPLE. NO TEXT or lettering of any kind unless specified. If any distant hillside appears above the rooftops it must be off-centre, hazy, less than 15 percent of image height, green with terraced vineyards, with NO crater, NO flat truncated top, NO notch, NO smoke. Avoid: anime, gothic or pointed arches, medieval, Renaissance, bell towers, church domes, chimneys, modern objects, watermarks, landscape orientation."

case "$1" in
harbour) F="p_harbour_01"; S="THE SUBJECT IS THE HARBOUR OF POMPEII IN 79 AD in the early morning. A stone quay stacked with two-handled amphorae in wooden racks, coils of rope, wicker baskets, a crane-like wooden hoist. Roman merchant sailing ships moored alongside with furled ochre square sails, curved swan-neck sterns and painted eyes on the bows. Warehouses with wide timber doors behind the quay. Cool dawn light, the sea still leaden. The masts and the hoist give the frame its vertical structure.";;
forum) F="p_forum_01"; S="THE SUBJECT IS THE FORUM OF POMPEII IN 79 AD, STILL UNDER REPAIR seventeen years after the earthquake of AD 62. A long colonnade of tall columns down one side - use them for the vertical structure of the tall frame. Clearly visible repair works: wooden scaffolding lashed against a wall, cut blocks of stone stacked under straw matting, a section of new pale masonry that has not yet weathered to match the old, tools left on a plank. Statue bases, some empty. Bright midday light.";;
thermopolium) F="p_thermopolium_01"; S="THE SUBJECT IS A THERMOPOLIUM, A ROMAN HOT FOOD COUNTER, IN POMPEII IN 79 AD, seen from the street looking in. A masonry counter faced with irregular coloured marble fragments, with large round earthenware dolia jars set into its top. Behind it a painted back wall with a small household shrine, shelves of cups and jugs, hanging bunches of herbs. A cloth awning over the entrance. Steam and warm interior light against the cooler street.";;
bakery) F="p_bakery_01"; S="THE SUBJECT IS A BAKERY IN POMPEII IN 79 AD. Two or three tall hourglass-shaped volcanic stone millstones standing in the yard, a domed brick bread oven with its arched mouth glowing, wooden racks and trays, sacks of grain, flour dust in a shaft of light from above. Use the millstones and the shaft of light for vertical structure.";;
peristyle) F="p_peristyle_01"; S="THE SUBJECT IS THE PERISTYLE GARDEN COURTYARD OF A ROMAN HOUSE IN POMPEII IN 79 AD. A colonnade of slender columns around a planted garden - use the columns and the open sky above for the vertical structure. A long narrow water basin, a marble table, a small fountain, clipped shrubs, a fig tree, painted garden frescoes on the enclosing wall with birds and foliage. Dappled late afternoon light.";;
baths) F="p_baths_01"; S="THE SUBJECT IS THE INTERIOR OF A ROMAN PUBLIC BATH IN POMPEII IN 79 AD - the warm room. A high barrel-vaulted ceiling with moulded stucco decoration and a round skylight opening - use the vault and the shaft of light for the vertical structure. A large basin, niches for clothes divided by small figures along the upper wall, marble benches, steam in the air, bronze oil lamps. Warm diffused light. This is the one place where a thick small pane of glass may appear in a high opening, but it must not be a regular gridded window.";;
isis) F="p_isis_temple_01"; S="THE SUBJECT IS THE TEMPLE OF ISIS IN POMPEII IN 79 AD, rebuilt only recently after the earthquake so its paint and stucco still look new and sharp-edged. A small temple on a podium with columns and a pediment, standing in an enclosed colonnaded courtyard. Egyptian elements blended with Roman architecture: palm motifs, sphinx statuettes, a small stone stair leading down into a sunken purgatorium basin that holds sacred water. Late afternoon light, quiet.";;
ludus) F="p_ludus_01"; S="THE SUBJECT IS THE GLADIATOR BARRACKS COURTYARD IN POMPEII IN 79 AD. A rectangular colonnaded training yard surrounded by small plain cells on two levels, a wooden staircase, wooden practice posts driven into the sand, racks of blunt training weapons and helmets, a water trough. Plain and functional, not heroic. Late afternoon shadow across the sand.";;
gate) F="p_gate_road_01"; S="THE SUBJECT IS A CITY GATE OF POMPEII AND THE ROAD OUTSIDE IT IN 79 AD, at dusk. A heavy stone gate with a rounded arch, and beyond it the road lined on both sides with Roman tombs - stone funerary monuments, altars and benches carved with inscriptions, cypress trees between them. Use the gate arch and the cypresses and tomb monuments for vertical structure. The walls turn deep red in the low sun.";;
*) echo "unknown key: $1"; exit 1;;
esac

cd "$OUT" || exit 1
codex exec --skip-git-repo-check --sandbox workspace-write "Use your image_gen tool to generate ONE image in PORTRAIT orientation, aspect ratio 9:16 (tall, vertical, about 1024x1792), then copy the generated file into the current directory as ${F}.png using cp, then run ls to verify it exists. Use this prompt: ${STYLE} ${S} ${RULES}" 2>&1 | tail -3

shift
if [ $# -gt 0 ]; then exec "$SELF" "$@"; fi
