#!/bin/zsh
SELF="${0:A}"
# 剩餘 13 個立繪基底（2:3 直幅）。用法: genchar3.sh <key> [<key> ...]
OUT="${SELF:h}/../美術測試"

STYLE="A PAINTED FIGURE STUDY FOR AN ARCHAEOLOGICAL RECONSTRUCTION ILLUSTRATION OF POMPEII. This is a PAINTING, not a photograph. Painted by the same hand that paints the architectural reconstruction views of the city: realistic digital matte painting, visible painterly handling in the fabric folds and the skin, softly painted edges, matte surface, no photographic depth of field, no lens blur, no studio vignette, no glossy highlights on the skin. Roman fresco palette of red ochre, yellow ochre, Egyptian blue, green earth, lime white, muted saturation."

FRAME="This is a VISUAL NOVEL CHARACTER SPRITE for a mobile game, PORTRAIT orientation aspect ratio 2:3. FRAMING, follow exactly: the top of the head sits about 8 percent down from the top edge; the figure is CROPPED AT THE WAIST at the bottom edge; the figure is CENTRED horizontally and fills about 70 percent of the frame width; the body is turned very slightly to one side, the head upright, the eyes looking at the viewer. LIGHTING, follow exactly: one soft key light from the UPPER LEFT at about 45 degrees, producing a visible soft shadow down the RIGHT side of the face and the RIGHT side of the neck; even flat illustration lighting elsewhere; NO rim light, NO dramatic chiaroscuro. BACKGROUND, follow exactly: one single completely FLAT UNIFORM MEDIUM GREY FIELD filling the entire background, absolutely even, NO vignette, NO gradient, NO darkening at the corners, NO cast shadow behind the figure, NO scenery. Expression: neutral and at rest, mouth closed - this is the base pose from which expression variants will be derived."

RULES="Historical accuracy for Pompeii in 79 AD: authentic Roman dress of woven wool or linen, draped and pinned or belted, NO buttons, NO zips, NO stitched modern tailoring. NO eyeglasses, NO modern hairstyle, NO modern makeup, NO weapons. NO text, NO lettering, NO watermark, NO signature, NO border. Avoid: photograph, photorealistic portrait photography, studio headshot, anime, cel shading, plastic skin, medieval or Renaissance costume, fantasy armour, landscape orientation."

case "$1" in
lender)   F="ch_lender_base";   S="THE CHARACTER: Quintus, a Roman moneylender of about fifty in Pompeii. He is NOT a villain and must not look like one - he is himself in debt. Build: narrow shoulders, slightly stooped from decades over accounts. Face: sallow, tired, deep lines from nose to mouth, thinning grey-brown hair combed forward, clean shaven, watchful eyes that calculate quickly and take no pleasure in it. Dress: a good quality but visibly worn dark ochre wool tunica, and a plain dull brown mantle over the left shoulder - clothes that were expensive some years ago. He holds a small wooden writing tablet against his chest.";;
zabda)    F="ch_zabda_base";    S="THE CHARACTER: Zabda, a Syrian employee of an Alexandrian trading house, about thirty-two. Build: lean, travelled, upright. Face: dark olive-brown skin, black close-cropped hair and a short neat black beard, sharp attentive eyes, an outsider's careful expression - polite and reserved. NOTABLE: long slender hands. Dress: a plain undyed linen tunica suited to shipboard work, belted, with a russet-brown travelling mantle over one shoulder. He carries a folding wooden writing tablet in one long-fingered hand. He is clearly not local.";;
priest)   F="ch_priest_base";   S="THE CHARACTER: the chief priest of the temple of Isis in Pompeii, about fifty-five. HISTORICALLY IMPORTANT: priests of Isis SHAVED THEIR HEADS COMPLETELY and wore plain WHITE LINEN - render him completely bald with no hair and no beard, in an unadorned white linen robe. Face: smooth, olive, heavy-lidded, patient, deeply intelligent, the face of a man who has spent thirty years managing what people are willing to believe. He holds nothing.";;
patron)   F="ch_patron_base";   S="THE CHARACTER: the twenty-three year old son of a wealthy freedman in Pompeii, who now manages his late father's endowments. Build: slim, well fed, holds himself straight. Face: smooth young olive skin, carefully arranged dark hair, clean shaven, a cool and slightly impatient expression - a young man who has never had to be liked. Dress: a very fine bleached wool tunica with narrow crimson stripes and a well draped cream mantle. Expensive and correct in every detail, which is itself the point.";;
thea)     F="ch_thea_base";     S="THE CHARACTER: Thea, a household slave of about forty-five who has been the nurse of a family's child since his birth. Build: solid, capable, practical. Face: weathered olive skin, dark hair greying and pulled back plainly under a simple cloth band, NO elaborate coiffure, kind but unsentimental eyes with lines at their corners. NOTABLE: a faint old pale SCAR about two fingers long on her RIGHT CHEEK. Dress: a plain undyed coarse wool tunica belted with a cord, sleeves pushed up, a dull brown shawl over one shoulder. Everything she wears is worn soft with washing.";;
salvia)   F="ch_salvia_base";   S="THE CHARACTER: Salvia, the wife of a Pompeian freedman merchant, about thirty-six, ambitious for her son. Build: neat, contained. Face: olive skin, alert eyes, mouth held slightly tight with the effort of managing everything; hair dressed carefully but not extravagantly, parted and bound with fillets. Dress: a good soft wool tunica in warm ochre with a fine deep red mantle, one modest gold-coloured earring and a simple bracelet - respectable, slightly more than the family can comfortably afford. She carries a small wax tablet, the household accounts.";;
master)   F="ch_master_base";   S="THE CHARACTER: Lucius, twenty-three, who inherited a Pompeian banking household two years ago and is out of his depth. Build: slight, soft-handed, not yet filled out. Face: young smooth olive skin, dark curls cut in the current fashion, clean shaven, an expression that is trying very hard to look authoritative and does not quite manage it. Dress: a fine white wool tunica with narrow stripes and a pale mantle, well made but slightly too formal for the time of day.";;
steward)  F="ch_steward_base";  S="THE CHARACTER: Felix, about fifty, the steward of a Pompeian household - a trusted slave or freedman who effectively runs the house. Build: sturdy, upright, a man permanently in motion. Face: broad weathered olive face, close-cropped grey hair, clean shaven, direct and competent eyes, jaw set. Dress: a plain sturdy undyed wool tunica, belted, with a leather strap over one shoulder carrying keys and a small tablet. Clean, practical, no ornament whatsoever.";;
hylas)    F="ch_hylas_base";    S="THE CHARACTER: Hylas, a twelve year old boy, a slave bought into a Pompeian household last year. Build: thin, small for his age, narrow shoulders. Face: young olive skin, dark tousled hair badly cut, large dark watchful eyes, mouth closed - a child who has learned to be quiet and to wait to be told what to do. Dress: a plain short undyed tunica, coarse cloth, belted with a cord, slightly too big for him. Bare arms, a little dirty.";;
orestes)  F="ch_orestes_base";  S="THE CHARACTER: Orestes, a gladiator of about thirty in the Pompeian barracks. He must look like a WORKING MAN, not a hero and not a warrior fantasy: no armour, no helmet, no weapon. Build: heavily muscled through the shoulders and forearms, thickened, marked. Face: broad, sun-darkened, a flattened nose, close-cropped dark hair, dark steady eyes, an expression of complete unexcitable calm. NOTABLE: a long old SCAR running down the outside of his LEFT UPPER ARM from shoulder to elbow. Dress: bare chested or a plain undyed cloth wrapped at the waist, and a simple wide leather belt. Nothing decorative.";;
pliny)    F="ch_pliny_base";    S="THE CHARACTER: the commander of the Roman fleet at Misenum, a scholar and naturalist, about fifty-six. NOTE: no authentic portrait of this man survives, so this is an imagined likeness in period-correct dress. Build: heavy, thick necked, short of breath - his laboured breathing should be legible in the set of his shoulders. Face: broad, fleshy, grey close-cut hair receding, clean shaven, deep-set eyes that are intensely curious rather than commanding; the face of a man observing something and composing a description of it. Dress: a fine white wool tunica with a dark red officer's mantle draped over the left shoulder. He holds a wooden writing tablet and a stylus, mid-note.";;
officer)  F="ch_officer_base";  S="THE CHARACTER: the sailing master of a Roman warship, about forty-two. Build: compact, hard, balanced. Face: deeply sun-darkened and creased, salt-bleached short brown hair, a few days of stubble, narrow eyes used to judging distance and weather, a mouth that gives orders and does not repeat them. Dress: a plain undyed working tunica belted at the waist with a wide leather belt, sleeves short, a coil of thin rope over one shoulder. Practical, no rank ornament.";;
survivor) F="ch_survivor_base"; S="THE CHARACTER: an old woman of about sixty-five selling eggs in a market at Puteoli, months after she escaped from Pompeii. Build: small, bent, wiry and durable. Face: deeply lined dark olive skin, thin white hair covered by a worn dull grey headcloth, sharp suspicious eyes that measure a stranger before answering, mouth pulled in. Dress: a much-mended coarse brown wool tunica and shawl, everything faded and re-dyed. She has nothing and she is not asking for anything.";;
*) echo "unknown: $1"; exit 1;;
esac

cd "$OUT" || exit 1
codex exec --skip-git-repo-check --sandbox workspace-write "Use your image_gen tool to generate ONE image in PORTRAIT orientation aspect ratio 2:3 (about 1024x1536), then copy the generated file into the current directory as ${F}.png using cp, then run ls to verify it exists. Use this prompt: ${STYLE} ${FRAME} ${S} ${RULES}" 2>&1 | tail -2

shift
if [ $# -gt 0 ]; then exec "$SELF" "$@"; fi
